# fonts #
global BUTTON_FONT
BUTTON_FONT = ("Arial", 11)
global BUTTON_FONT_COLOR
BUTTON_FONT_COLOR = "white"

global DATA_FONT
DATA_FONT = ("Arial", 10)
global DATA_FONT_COLOR
DATA_FONT_COLOR = "black"

global TOOLBAR_ACC_FONT
TOOLBAR_ACC_FONT = ("Arial", 10)

global PICK_FONT
PICK_FONT = ("Arial", 9)

# background colors #
global TRANS_GREEN
TRANS_GREEN = "#6b9169"
global TRANS_RED
TRANS_RED = "#e6594c"

global BUTTON_COLOR
BUTTON_COLOR = "#505558"
global BUTTON_BAR_BUTTON_COLOR
BUTTON_BAR_BUTTON_COLOR = "#404040"

global DATA_COLOR
DATA_COLOR = "white"

global TOOLBAR_BG
TOOLBAR_BG = "#808588"
global INNER_FRAME_BG
INNER_FRAME_BG = "white"
global INNER_FRAME_DATA_BG
INNER_FRAME_DATA_BG = "#dedede"

# sizes #

global WINDOW_SIZE
WINDOW_SIZE = "820x700"
global WINDOW_WIDTH
WINDOW_WIDTH = 820

global ACCOUNT_NAME_SIZE
ACCOUNT_NAME_SIZE = 20
global CATEGORY_NAME_SIZE
CATEGORY_NAME_SIZE = 20
